### ISSUE TITLE
Minimum Viable JobRequests

### ISSUE THREAD

**Issue by ghickman** [opensafely/job-server#100]
This issue will serve as a roadmap for getting to "1.0" with the various changes to job-server around how we'd like to group jobs (JobRequest) and how we'd like job-server and job-runner to interact.

Please feel free to update the issue body with changes as you see fit, discussion can happen in comments as usual.

---

Tasks in order of expected completion:

* [x] Add `JobRequest` shims to `/api/job/` (#99)
* [x] Set up GitHub Access Tokens (#91)
* [x] List available project.yaml Actions from GitHub (#90)
* [x] List available repos from GitHub (#92)
* [x] List available branches from GitHub
* [x] Build `GET /api/job-requests/`
* [x] Build `POST /api/job-requests/` endpoint
* [x] Filter `JobRequest`s by User (#86)
* [x] Redirect Users to their own Jobs (#98)

**Comment by sebbacon** [comment]
Can this be closed @ghickman ?

**Comment by ghickman** [comment]
Yes 🎉
